name: CI
on:
  push:
    branches:
      - develop
jobs:
  ci:
    name: Test - Unit & Integration & CodeQL Analysis & SonarCloud Scan & Slack WebHook
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode
      - name: Initialize CodeQL
        if: success()
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: security-extended
      - name: Build project
        if: success()
        run: mvn clean compile
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"
      - name: Slack WebHook
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,author,commit,author,workflow, # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      - name: Sonar
        if: success() # always() failure() success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=InvierteIO_tfm-user-srv
          -Dsonar.organization=invierteio
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.token=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPOS_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
